builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: micnncim
    name: homebrew-tap
  folder: Formula
  description: "chcase: CLI changing string cases"
  homepage: "https://github.com/micnncim/chcase"
  install: |
    bin.install "chcase"
  test: |
    system "#{bin}/chcase"
